const data = {
  products: [
    {
      name: "Think And Grow Rich",
      slug: "think-and-grow-rich",
      image: "/imagess/tagh.png",
      price: 120,
      countInStock: 10,
      writer: "Nepolian Hill",
      rating: 4.5,
      numReviews: 10,
      description: "self help and motivational book",
    },
    {
      name: "Alchemist",
      slug: "alchemist",
      image: "/imagess/alchemist.jpeg",
      price: 150,
      countInStock: 20,
      writer: "Paulo Coelho",
      rating: 4,
      numReviews: 7,
      description: "story of the great person",
    },
    {
      name: "Steve Jobs",
      slug: "steve-jobs",
      image: "/imagess/steve.jpeg",
      price: 200,
      countInStock: 15,
      writer: "Walter Isaacson",
      rating: 4.7,
      numReviews: 3,
      description: "biography of apple ceo steve jobs",
    },
    {
      name: "Think Like a Monk",
      slug: "think-like-a-monk",
      image: "/imagess/tlam.jpeg",
      price: 300,
      countInStock: 40,
      writer: "Jay Sheety",
      rating: 4.2,
      numReviews: 26,
      description: "a book to help people to implement the life of the monk",
    },
    {
      name: "Rich Dad Poor Dad",
      slug: "rich-dad-poor-dad",
      image: "/imagess/rdpd.jpeg",
      price: 175,
      countInStock: 40,
      writer: "Jay Sheety",
      rating: 4.2,
      numReviews: 26,
      description: "a book to help people to implement the life of the monk",
    },
    {
      name: "Ijoriya",
      slug: "ijoriya",
      image: "/imagess/ijoriya.jpeg",
      price: 250,
      countInStock: 25,
      writer: "Subin Bhattrai",
      rating: 4.9,
      numReviews: 26,
      description: "story of a common man",
    },
    {
      name: "Sapiens",
      slug: "sapiens",
      image: "/imagess/sapiens.jpeg",
      price: 500,
      countInStock: 25,
      writer: "Yuval Noah",
      rating: 3.9,
      numReviews: 16,
      description: "A brief history of human kind",
    },
    {
      name: "Wolf Hall",
      slug: "wolf-hall",
      image: "/imagess/wh.jpeg",
      price: 375,
      countInStock: 7,
      writer: "Hilary Mantel",
      rating: 4.0,
      numReviews: 26,
      description: "A biography set in different period",
    },
  ],
};
export default data;
